from core.exceptions import NotFoundError


# class TaskNotFoundError(NotFoundError):
#     """Task not found"""
#
#     def __init__(self):
#         super().__init__(entity="Task")
